import type { RegistryEntry } from "../../shared.ts";

const COMMAND_CODE_REASONING_EFFORTS = ["low", "medium", "high", "xhigh", "max"] as const;

export const command_codeProvider: RegistryEntry = {
  id: "command-code",
  alias: "cmd",
  format: "openai",
  executor: "command-code",
  baseUrl: "https://api.commandcode.ai",
  // Chat uses the documented /provider/v1/chat/completions (OpenAI-format)
  // endpoint — NOT the CLI-only /alpha/generate endpoint, which Command Code
  // version-gates and proxy-blocks for external callers (#10265). Discovery
  // already targets the sibling /provider/v1/models endpoint.
  chatPath: "/provider/v1/chat/completions",
  modelsUrl: "https://api.commandcode.ai/provider/v1/models",
  // claude-* models are served ONLY on the Anthropic Messages endpoint (live
  // catalog: supported_endpoints ["/messages"]); /provider/v1/chat/completions
  // rejects them with 400 "must be called via /provider/v1/messages (Anthropic
  // Messages shape)". Each claude-* entry below carries targetFormat: "claude"
  // (getModelTargetFormat also maps any live-discovered claude-* id), so
  // chatCore translates the request to Anthropic Messages and
  // CommandCodeExecutor posts it here. Non-claude models keep chatPath.
  // The discovery response is a partial routing catalog; static registry
  // entries omitted from it can still be accepted by the gateway.
  liveCatalogAuthoritative: false,
  messagesUrl: "https://api.commandcode.ai/provider/v1/messages",
  authType: "apikey",
  authHeader: "Authorization",
  authPrefix: "Bearer ",
  defaultContextLength: 200000,
  models: [
    {
      id: "claude-opus-5-5",
      targetFormat: "claude",
      name: "Claude Opus 5.5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-opus-5",
      targetFormat: "claude",
      name: "Claude Opus 5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-opus-4-8",
      targetFormat: "claude",
      name: "Claude Opus 4.8 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-sonnet-5",
      targetFormat: "claude",
      name: "Claude Sonnet 5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 16384,
    },
    {
      id: "claude-fable-5",
      targetFormat: "claude",
      name: "Claude Fable 5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-fable-5-1",
      targetFormat: "claude",
      name: "Claude Fable 5.1 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-opus-4-7",
      targetFormat: "claude",
      name: "Claude Opus 4.7 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-opus-4-6",
      targetFormat: "claude",
      name: "Claude Opus 4.6 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-sonnet-4-6",
      targetFormat: "claude",
      name: "Claude Sonnet 4.6 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 16384,
    },
    {
      id: "claude-haiku-4-5-20251001",
      targetFormat: "claude",
      name: "Claude Haiku 4.5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 8192,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 256000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 256000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3 Codex (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 256000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 Mini (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 256000,
      maxOutputTokens: 128000,
    },
    {
      id: "deepseek/deepseek-v4-pro",
      name: "DeepSeek V4 Pro (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 1000000,
      maxOutputTokens: 131072,
    },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 1000000,
      maxOutputTokens: 131072,
    },
    {
      id: "moonshotai/Kimi-K2.6",
      name: "Kimi K2.6 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 262144,
      maxOutputTokens: 65536,
    },
    {
      id: "moonshotai/Kimi-K2.5",
      name: "Kimi K2.5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 262144,
      maxOutputTokens: 65536,
    },
    {
      id: "zai-org/GLM-5.1",
      name: "GLM-5.1 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 200000,
      maxOutputTokens: 32768,
    },
    {
      id: "zai-org/GLM-5",
      name: "GLM-5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 200000,
      maxOutputTokens: 32768,
    },
    {
      id: "MiniMaxAI/MiniMax-M2.7",
      name: "MiniMax M2.7 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 1048576,
      maxOutputTokens: 65536,
    },
    {
      id: "MiniMaxAI/MiniMax-M2.5",
      name: "MiniMax M2.5 (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 1048576,
      maxOutputTokens: 65536,
    },
    {
      id: "Qwen/Qwen3.6-Max-Preview",
      name: "Qwen 3.6 Max (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      contextLength: 1000000,
      maxOutputTokens: 32768,
    },
    {
      id: "Qwen/Qwen3.6-Plus",
      name: "Qwen 3.6 Plus (CC)",
      supportsReasoning: true,
      supportedThinkingEfforts: COMMAND_CODE_REASONING_EFFORTS,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 32768,
    },
  ],
};
